### ISSUE TITLE
copy_id not recognized

### ISSUE THREAD

**Issue by jkarlsen** [ExLibrisGroupCloudApps/hep-CloudApp-ItemCreator-Excel#1]
When creating items with a column labeled copy_id, I get the following error:

> Error: 
Unrecognized field "copy_id" (class com.exlibris.alma.ws.jaxb.item.ItemData), not marked as ignorable (76 known properties: "barcode", "retention_reason", "public_note", "imprint", "process_type", "pid", "inventory_number", "creation_date", "due_date_policy", "due_date", "base_status", "provenance", "receiving_operator", "receive_number", "inventory_price", "alt_call_no", "inventory_date", "policy", "year_of_issue", "po_line", "location", "alternative_call_number", "library", "edition", "linking_number", "statistics_note_2", "chronology_i", "chronology_j", "pages", "pieces", "chronology_m", "break_indicator", "issue_date", "language", "replacement_cost", "expected_arrival_date", "alternative_call_number_type", "internal_note_1", "type_of_unit", "internal_note_3", "enumeration_a", "physical_material_type", "enumeration_c", "enumeration_d", "enumeration_e", "requested", "enumeration_g", "enumeration_h", "modification_date", "weeding_number", "is_magnetic", "description", "pattern_type", "title_abcnph", "storage_location_id", "work_order_at", "arrival_date", "alt_number_source", "library_details" [truncated]])
 at [Source: (ByteArrayInputStream); line: 1, column: 53] (through reference chain: com.exlibris.alma.ws.jaxb.item.Item["item_data"]->com.exlibris.alma.ws.jaxb.item.ItemData["copy_id"])

copy_id a pretty significant field to leave out of the application, if that is what is happening here. Please add support for this field.

**Comment by SSund24** [comment]
I get the same error "Unrecognized field..." for the following temp location-related elements:
in_temp_location | temp_library | temp_location | temp_policy
I also got same message for copy_id.

These elements all appear on the list for subsequent columns linked from:  https://developers.exlibrisgroup.com/appcenter/item-creator-by-excel/ : 
"subsequent columns: item record details. See https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_item.xsd for the name of fields to use in the column header."

This would be a *great* tool if this problem could be fixed.

**Comment by SSund24** [comment]
The error message no longer seems to display for the above fields (copy_id and the temp location-related elements).  The item record is created, BUT the desired values are NOT added to the item record (tested in Sandbox).

**Comment by ksfez** [comment]
Hey, I am sorry for the delay. 
I will check this issue and update you about the copy_id field. If it is not supported I will update the documentation.
Thanks

**Comment by SSund24** [comment]
Thanks, @ksfez 
I've been doing some more testing and discovered something that may or may not have anything to do with this trouble with copy_id and in_temp_location | temp_library | temp_location | temp_policy ...

I noticed that in the data dictionary here: https://developers.exlibrisgroup.com/alma/apis/xsd/rest_item.xsd/?tags=PUT#item_data
... all five of these fields are listed as as "holding_data" 
Although copy number is indeed a MARC holdings element, it also is separately entered in the item record, so should be listed in item_data 
And temp_location | temp_library | temp_location | temp_policy  all also appear under data dictionary's "holding_data" 
Location is a MARC holdings element (https://www.loc.gov/marc/holdings/hd852.html ) but *temporary* location is not.  These temporary location fields are, I believe, incorrectly listed in the data dictionary's "holding_data" and should be in "item_data" just as copy_id should be
Apologies if this particular data dictionary has nothing to do with the Cloud App!

**Comment by ksfez** [comment]
Hi,
Thanks for your comments! I have fixed these issues in the Third Release of the application.
I close this issue for now. Please feel free to re-open if after upgrading to v3.0 it is still not working.
Thanks,
Keren
