### ISSUE TITLE
 Error message not displaying when it should

### ISSUE THREAD

**Issue by SSund24** [ExLibrisGroupCloudApps/hep-CloudApp-ItemCreator-Excel#2]
@ori229 @ksfez
I also added this under a comment for Issue 1. Please see issue 1 as well.
No error message now displays (nor is item creation disalllowed) for the case where fields copy_id, in_temp_location, temp_library, temp_location, and temp_policy are in the spreadsheet but are not added to the new item record.
The item record is created, BUT the desired values are NOT added to the item record (tested in Sandbox).

**Comment by ksfez** [comment]
Hi. I will check this issue as well and update you about the error messages.
Thanks

**Comment by ksfez** [comment]
Hi,
This is fixed in the Third Release.
I close this issue, please feel free to re-open one if it is still not working after upgrading to v3.0
Thanks
Keren
