### ISSUE TITLE
Temporary Locations not nested under 'holding' in json

### ISSUE THREAD

**Issue by selamarin** [ExLibrisGroupCloudApps/hep-CloudApp-ItemCreator-Excel#3]
The following fields are not being added to items because the script 'cloudapp/src/app/main/item.service.ts' is nesting them under the 'item_data' element instead of the 'holding_data' element in the json:

copy_id
in_temp_location
temp_library
temp_location
temp_call_number_type
temp_call_number
temp_call_number_source
temp_policy
due_back_date

These fields would be incredibly beneficial to be able to add with this cloudapp. See lines 55-65 in 'cloudapp/src/app/main/item.service.ts' that need to be reworked.

(Apologies -- this was initially reported in the Updater app, but it was meant for the Creator app)

**Comment by ksfez** [comment]
Hi,

Thanks for your comment! I have fixed it in the Third Release of this application.
I close for now this issue, please feel free to re-open if it is still not working after upgrade to v3.0

Thanks,
Keren
